### PR TITLE
Added ablity to get popular movies

### PR DESCRIPTION
**Pull request by aagavin**

### CODE REVIEW

**Comment by richardasaurus** [comment]
Sorry just saw this, will review this weekend

**Comment by aagavin** [comment]
Any update?

**Comment by richardasaurus** [comment]
can you remove the `.cache` file and add that to gitignore? then happy to merge and will make a release

**Comment by aagavin** [comment]
Done

**Comment by richardasaurus** [comment]
@aagavin released in `4.3.0`

**Pull request merged**
