### PR TITLE
Add new methods

### PR DESCRIPTION
**Pull request by duramato**
Implements https://github.com/richardasaurus/imdb-pie/issues/55

### CODE REVIEW

**Comment by duramato** [comment]
I was able to implement all methods I wanted, except 2, which are these (from android):
-https://api.imdbws.com/template/imdb-android-writable/7.3.title-series-seasons-summary.jstl/
render?currentCountry=XX&homeCountry=XX&purchaseCountry=XX&postalcode=XX&today=2018-01-12&distance=100000&marketplace=XX&tvpostalcode=90028&tconst=tt3655448
-https://api.imdbws.com/template/imdb-android-writable/7.3.top-crew.jstl/render?tconst=tt3655448 

@richardasaurus Could you maybe see if you find these on iOS? The endpoints are different between Android and iOS, I was able to "guess" all I've implemented based on a pattern I see, but these 2 I couldn't. Thanks

**Comment by richardasaurus** [comment]
Looks good except there are some lint errors, I guess it's not running the linter on CI. Can you run `flake8` locally and fix those up? Then it's good to merge 👍

**Comment by p0psicles** [comment]
@richardasaurus can you help us with 7.3.title-series-seasons-summary.jstl? That's actually the most valuable one for us.

**Comment by richardasaurus** [comment]
What data are you trying to get?

**Comment by duramato** [comment]
All of the info in that enpoint is important to us haha but THE MOST important there, is the `release` key for each `episode`, ex:`"release":"2017-01-15"` 
I haven't been able to find that info on any other endpoint.

**Comment by richardasaurus** [comment]
On ios, this path returns that sort of info is `/template/imdb-ios-writable/tv-episodes-v2.jstl/` 

but I couldn't guess the API url yet to find that. Worst case you'd have to call `get_title_releases` for each episode imdb_id, which is not ideal.

**Comment by p0psicles** [comment]
Yeah where trying to avoid that

**Comment by richardasaurus** [comment]
One way to maybe discover a url to provide that info is to download all the previous app APKs (https://www.apkmirror.com/apk/imdb/) decompile them and look at the url routes in the source code. Perhaps an older app version called some endpoint which the new one no longer does.

**Comment by duramato** [comment]
@richardasaurus I've been exploring the imdb apk code, even for the oldest version i could get (from 2014), and they all call `title-series-seasons-summary.jstl`

At `com.imdb.mobile.mvp.modelbuilder.title.TitleSeasonsModelBuilder.java`
Snippet of it https://gist.github.com/duramato/51d4c4d3b017700f397ff1c9fece66b4

**Comment by vsego** [comment]
@richardasaurus 

> but I couldn't guess the API url yet to find that. Worst case you'd have to call get_title_releases for each episode imdb_id, which is not ideal.

I agree that it's not ideal, and it also doesn't seem to work. I get `LookupError` exception when I try to call `imdb.get_title_releases(imdb_id)` for an episode's IMDb ID (for example, `"tt7820276"`).

Is there another way to get episodes' release date?

**Comment by richardasaurus** [comment]
@vsego that imdb is just a random one which it does not work for, try with this one and it works http://www.imdb.com/title/tt4341176/

**Comment by vsego** [comment]
@richardasaurus Ah, thank you. It turned out to be a bug in my code, that kept calling `get_title_releases` for the same episode, instead of the one from the loop (for which I was verifying that there actually *are* release dates).

**Comment by VeNoMouS** [comment]
Is this the url you are after for episodes? `https://api.imdbws.com/template/imdb-ios-writable/tv-episodes-v2.jstl/render?end=500&region=XX&season=0&start=0&tconst=tt3655448`

```
{
	"season": 1,
	"seriesTitle": {
		"id": "/title/tt3655448/",
		"image": {
			"height": 2048,
			"id": "/title/tt3655448/images/rm897516800",
			"url": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODA2NjAxMV5BMl5BanBnXkFtZTgwMTUzOTA4MDI@._V1_.jpg",
			"width": 1382
		},
		"runningTimeInMinutes": 546,
		"nextEpisode": "/title/tt4897554/",
		"numberOfEpisodes": 10,
		"seriesStartYear": 2016,
		"title": "The Young Pope",
		"titleType": "tvSeries",
		"year": 2016
	},
	"allSeasons": [
		1
	],
	"totalEpisodes": 10,
	"start": 0,
	"end": 500,
	"region": "NZ",
	"episodes": [
		{
			"episodeNumber": 1,
			"id": "/title/tt4897554/",
			"title": "Episode #1.1",
			"year": 2016,
			"rating": 8.1,
			"userRating": null,
			"ratingCount": 1151,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-10-21",
					"regions": [
						"DE",
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 2,
			"id": "/title/tt4897556/",
			"title": "Episode #1.2",
			"year": 2016,
			"rating": 8.3,
			"userRating": null,
			"ratingCount": 896,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-10-21",
					"regions": [
						"DE",
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 3,
			"id": "/title/tt4897560/",
			"title": "Episode #1.3",
			"year": 2016,
			"rating": 8.1,
			"userRating": null,
			"ratingCount": 776,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-10-28",
					"regions": [
						"DE",
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 4,
			"id": "/title/tt4897562/",
			"title": "Episode #1.4",
			"year": 2016,
			"rating": 8.1,
			"userRating": null,
			"ratingCount": 713,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-10-28",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 5,
			"id": "/title/tt4897564/",
			"title": "Episode #1.5",
			"year": 2016,
			"rating": 8.6,
			"userRating": null,
			"ratingCount": 718,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-04",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 6,
			"id": "/title/tt4897566/",
			"title": "Episode #1.6",
			"year": 2016,
			"rating": 8.2,
			"userRating": null,
			"ratingCount": 619,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-04",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 7,
			"id": "/title/tt4897572/",
			"title": "Episode #1.7",
			"year": 2016,
			"rating": 8,
			"userRating": null,
			"ratingCount": 583,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-11",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 8,
			"id": "/title/tt4897574/",
			"title": "Episode #1.8",
			"year": 2016,
			"rating": 8.7,
			"userRating": null,
			"ratingCount": 687,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-11",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 9,
			"id": "/title/tt5980380/",
			"title": "Episode #1.9",
			"year": 2016,
			"rating": 8.9,
			"userRating": null,
			"ratingCount": 758,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-18",
					"regions": [
						"IT",
						"US"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		},
		{
			"episodeNumber": 10,
			"id": "/title/tt5980392/",
			"title": "Episode #1.10",
			"year": 2016,
			"rating": 8.8,
			"userRating": null,
			"ratingCount": 705,
			"releaseDate": {
				"date": null,
				"first": {
					"date": "2016-11-18",
					"regions": [
						"IT"
					]
				}
			},
			"watchOptions": {
				"hasInstant": false,
				"hasDisk": false
			}
		}
	]
}```

**Comment by p0psicles** [comment]
@VeNoMouS how would I implement this? Is this the same endpoint as what we've been communicating with?

**Comment by duramato** [comment]
@VeNoMouS that one doesn't work with the auth imdb-pie uses, or at least it didn't work when I tried.

**Comment by VeNoMouS** [comment]
This is because @richardasaurus didn't write _get() correctly... he has not incorporated the variable `query` into the into the header auth signage.

```
        path = urlparse(url).path
```

to

```
        path = urlparse(url).path
        if query:
            path += '?'  + urlencode(query)
```

and adding query into the `requests.get()` request... 

```resp = self.session.get(url, headers=headers, params=query)```

And simply testing by creating a function such as ...

```
    def get_episodes(self, imdb_id):
        url = "https://api.imdbws.com/template/imdb-ios-writable/tv-episodes-v2.jstl/render"
        query = {'end': 500, 'region': 'NZ', 'season': 0, 'start': 0, 'tconst': imdb_id } 
        search_results = self._get(url=url, query=query)
        pprint(search_results);
```

**Comment by VeNoMouS** [comment]
Lets hope @richardasaurus doesn't delete all the chat history this time 😉

**Comment by p0psicles** [comment]
I almost all did this. Except adding the URL encoded string to the path var. It complained about a bad Amazon authentication. So I guess that's the path.

Tnx a million @VeNoMouS

**Comment by p0psicles** [comment]
@richardasaurus i'll fix this route in a separate PR. Can you help us getting this PR finished?

**Comment by p0psicles** [comment]
@duramato I also still need the companies route. But i'll add that myself, after this PR has been merged.

**Comment by duramato** [comment]
I've added it @p0psicles

**Pull request merged**
